export const demoUsers = {
  teen: {
    uid: 'demo-teen',
    email: 'teen@churro.app',
    fullName: 'Maya Lopez',
    role: 'teen',
    dateOfBirth: '2010-05-12',
    age: 15,
    linkedParentUid: 'demo-parent',
    parentApproved: true,
    bio: 'Reliable with errands and pet care.',
    approvedCategories: ['grocery_run', 'pet_care', 'tech_help', 'babysitting'],
    radiusLimit: 1,
    balance: 42,
    totalEarned: 180,
    completedTasks: 6,
    averageRating: 4.8,
    weeklyEarnings: {
      '2026-W14': 30,
      '2026-W15': 60,
      '2026-W16': 42,
      '2026-W17': 48
    }
  },
  parent: {
    uid: 'demo-parent',
    email: 'parent@churro.app',
    fullName: 'Carlos Lopez',
    role: 'parent',
    linkedTeenUid: 'demo-teen',
    teenRadiusLimit: 1,
    approvedCategories: ['grocery_run', 'pet_care', 'tech_help', 'babysitting'],
    weeklyEarningsCap: 150,
    autoApprove: false
  },
  neighbors: [
    {
      uid: 'demo-neighbor-1',
      email: 'neighbor1@churro.app',
      fullName: 'Sarah Miller',
      role: 'neighbor',
      address: '123 Maple Ave, San Francisco, CA',
      verified: true,
      averageRating: 4.2,
      completedTasks: 18
    },
    {
      uid: 'demo-neighbor-2',
      email: 'neighbor2@churro.app',
      fullName: 'Jordan Patel',
      role: 'neighbor',
      address: '88 Oak Street, San Francisco, CA',
      verified: true,
      averageRating: 4.8,
      completedTasks: 26
    },
    {
      uid: 'demo-neighbor-3',
      email: 'neighbor3@churro.app',
      fullName: 'Priya Chen',
      role: 'neighbor',
      address: '42 Pine Road, San Francisco, CA',
      verified: true,
      averageRating: 3.9,
      completedTasks: 11
    }
  ]
};

export const demoTasks = [
  {
    taskId: 'demo-task-1',
    neighborUid: 'demo-neighbor-1',
    neighborName: 'Sarah',
    neighborAddress: '123 Maple Ave, San Francisco, CA',
    neighborRating: 4.2,
    category: 'grocery_run',
    requiresPowerTools: false,
    title: 'Grocery run',
    description: 'Pick up a short grocery list from the market and drop it off at the house.',
    specialInstructions: 'Use the side entrance.',
    pay: 18,
    date: '2026-04-19',
    startTime: '14:00',
    endTime: '16:00',
    status: 'open',
    applicantTeenUid: null,
    teenName: null,
    teenRating: null,
    teenCheckInStatus: 'none',
    neighborConfirmed: false,
    latitude: 37.7762,
    longitude: -122.4241
  },
  {
    taskId: 'demo-task-2',
    neighborUid: 'demo-neighbor-2',
    neighborName: 'Jordan',
    neighborAddress: '88 Oak Street, San Francisco, CA',
    neighborRating: 4.8,
    category: 'pet_care',
    requiresPowerTools: false,
    title: 'Dog walking',
    description: 'Walk a friendly medium-size dog for about 30 minutes.',
    specialInstructions: 'Bring a water bowl back inside.',
    pay: 12,
    date: '2026-04-20',
    startTime: '09:00',
    endTime: '10:00',
    status: 'open',
    applicantTeenUid: null,
    teenName: null,
    teenRating: null,
    teenCheckInStatus: 'none',
    neighborConfirmed: false,
    latitude: 37.779,
    longitude: -122.414
  },
  {
    taskId: 'demo-task-3',
    neighborUid: 'demo-neighbor-3',
    neighborName: 'Priya',
    neighborAddress: '42 Pine Road, San Francisco, CA',
    neighborRating: 3.9,
    category: 'tech_help',
    requiresPowerTools: false,
    title: 'TV setup',
    description: 'Mount the TV on the stand and connect streaming apps.',
    specialInstructions: 'No drilling required.',
    pay: 20,
    date: '2026-04-18',
    startTime: '16:00',
    endTime: '18:00',
    status: 'open',
    applicantTeenUid: null,
    teenName: null,
    teenRating: null,
    teenCheckInStatus: 'none',
    neighborConfirmed: false,
    latitude: 37.7715,
    longitude: -122.4311
  },
  {
    taskId: 'demo-task-4',
    neighborUid: 'demo-neighbor-1',
    neighborName: 'Sarah',
    neighborAddress: '123 Maple Ave, San Francisco, CA',
    neighborRating: 4.2,
    category: 'babysitting',
    requiresPowerTools: false,
    title: 'Babysitting',
    description: 'Supervise two kids during dinner and bedtime.',
    specialInstructions: 'Parent will be upstairs.',
    pay: 25,
    date: '2026-04-19',
    startTime: '18:00',
    endTime: '21:00',
    status: 'open',
    applicantTeenUid: null,
    teenName: null,
    teenRating: null,
    teenCheckInStatus: 'none',
    neighborConfirmed: false,
    latitude: 37.7683,
    longitude: -122.4235
  },
  {
    taskId: 'demo-task-5',
    neighborUid: 'demo-neighbor-2',
    neighborName: 'Jordan',
    neighborAddress: '88 Oak Street, San Francisco, CA',
    neighborRating: 4.8,
    category: 'yard_power',
    requiresPowerTools: true,
    title: 'Yard cleanup with power tools',
    description: 'Trim hedges and use the leaf blower in the front yard.',
    specialInstructions: 'Equipment is provided.',
    pay: 30,
    date: '2026-04-20',
    startTime: '10:00',
    endTime: '13:00',
    status: 'open',
    applicantTeenUid: null,
    teenName: null,
    teenRating: null,
    teenCheckInStatus: 'none',
    neighborConfirmed: false,
    latitude: 37.7812,
    longitude: -122.418
  }
];
